# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abc59824a7249766b1ca5fdad9f0b3378c208f3cdb9daae40a8d6d1d7e102ad1c7d3746cdb5cb16ddacaec18b8f6bc611cbe353c2785f2ea127db378adb7a68e

test:
  secret_key_base: 6f8313696f67ce58300eff570a126d7e99b4c4074bfd4aedceedf4f0681753d293e28e15330669d4effac82d0680973eb7f587ef7084689efdb18eb47b19c583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
